services:
  bayshore:
    image: ${BAYSHORE_IMAGE:-ghcr.io/projectasakura/bayshore:latest}
    ports:
      - 80:80
      - 10082:10082
      - 9002:9002
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config.json:/home/node/config.json
    init: true
  db:
    image: docker.io/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: bayshore
      POSTGRES_PASSWORD: bayshore
      POSTGRES_DB: bayshore
    ports:
      - 6432:5432
    volumes:
      - bayshore_data:/var/lib/postgresql/data
      - ./sql-files:/root/sql-files
    working_dir: /root/sql-files

volumes:
  bayshore_data:
