services:
  bayshore:
    build: .
    volumes:
      - ./:/src
    ports:
      - 8080:80
      - 10082:10082
      - 9002:9002
    restart: unless-stopped
    env_file: .env
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 6432:5432
    volumes:
      - bayshore_data_dockerized:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 5050:80

volumes:
  bayshore_data_dockerized:
