# The production bayshore docker compose file is totally different from this one
# this one it should work for the most part for a generic setup lmao
# feel free to change this - AzuriDayo

services:
  bayshore:
    # This defaults to using ProjectAsakura's bayshore image if not overridden from .env
    image: ${OVERRIDE_BAYSHORE_IMAGE:-ghcr.io/projectasakura/bayshore:latest}
    ports:
      - 80:80
      - 10082:10082
      - 9002:9002
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config.json:/home/node/config.json
    init: true # <- Ya fuck nodejs this is required to make it work well
  postgres:
    image: docker.io/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: bayshore
      POSTGRES_PASSWORD: bayshore
      POSTGRES_DB: bayshore
    ports:
      - 5432:5432
    volumes:
      - bayshore_data:/var/lib/postgresql/data
      - ./sql-files:/root/sql-files
    working_dir: /root/sql-files

volumes:
  bayshore_data:
