name: Publish container

on:
  push:
    branches: [dockerized-node22]

jobs:
  build:
    strategy:
      matrix:
        build-targets:
          - label: ubuntu-latest
            arch: amd64
          - label: ubuntu-24.04-arm64
            arch: arm64
          - label: ubuntu-24.04-arm64
            arch: arm32v7
    permissions:
      contents: read
      packages: write
    name: Build Container for ${{ matrix.build-targets.arch }}
    runs-on: ${{ matrix.build-targets.label }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker buildx build --platform linux/${{ matrix.build-targets.arch }} --load -t bayshore .
          docker image tag bayshore ghcr.io/${{ github.repository_owner }}/bayshore:manifest-${{ matrix.build-targets.arch }}-${{ github.sha }}
          docker image push ghcr.io/${{ github.repository_owner }}/bayshore:manifest-${{ matrix.build-targets.arch }}-${{ github.sha }}
  merge-container:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker pull ghcr.io/${{ github.repository_owner }}/bayshore:manifest-arm32v7-${{ github.sha }}
          docker pull ghcr.io/${{ github.repository_owner }}/bayshore:manifest-arm64-${{ github.sha }}
          docker pull ghcr.io/${{ github.repository_owner }}/bayshore:manifest-amd64-${{ github.sha }}
          docker manifest create ghcr.io/${{ github.repository_owner }}/bayshore:latest \
            --amend ghcr.io/${{ github.repository_owner }}/bayshore:manifest-arm32v7-${{ github.sha }} \
            --amend ghcr.io/${{ github.repository_owner }}/bayshore:manifest-arm64-${{ github.sha }} \
            --amend ghcr.io/${{ github.repository_owner }}/bayshore:manifest-amd64-${{ github.sha }}
