name: Publish container

on:
  push:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        build-targets:
          - label: ubuntu-latest
            arch: amd64
            manifest-name: x64
          - label: ubuntu-24.04-arm
            arch: arm64
            manifest-name: arm64
    permissions:
      contents: read
      packages: write
    name: Build Container for ${{ matrix.build-targets.manifest-name }}
    runs-on: ${{ matrix.build-targets.label }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Build image
        run: |
          pnpm i --frozen-lockfile
          # Remove this when submiting PRs in other repos
          if [ -e ./personal-patches/apply-patches.mjs ]; then ./personal-patches/apply-patches.mjs; fi
          pnpm run build
          export PRISMA_VERSION=$(yq '.importers["."].devDependencies.prisma.version' -r <pnpm-lock.yaml)

          # First, lowercase-ify owner
          export owner=${{ github.repository_owner }}
          export owner=${owner,,}
          docker buildx build \
            --build-arg PRISMA_VERSION="$PRISMA_VERSION" \
            --platform linux/${{ matrix.build-targets.arch }} \
            --push \
            -t "ghcr.io/${owner}/bayshore:${{ matrix.build-targets.manifest-name }}-${{ github.sha }}" \
            -t "ghcr.io/${owner}/bayshore:${{ matrix.build-targets.manifest-name }}-latest" \
            --provenance false \
            .
  merge-container:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge images
        run: |
          # First, lowercase-ify owner
          export owner=${{ github.repository_owner }}
          export owner=${owner,,}
          docker manifest create "ghcr.io/${owner}/bayshore:latest" \
            --amend "ghcr.io/${owner}/bayshore:arm64-${{ github.sha }}" \
            --amend "ghcr.io/${owner}/bayshore:x64-${{ github.sha }}"
          docker manifest push "ghcr.io/${owner}/bayshore:latest"

          docker manifest create "ghcr.io/${owner}/bayshore:${{ github.sha }}" \
            --amend "ghcr.io/${owner}/bayshore:arm64-${{ github.sha }}" \
            --amend "ghcr.io/${owner}/bayshore:x64-${{ github.sha }}"
          docker manifest push "ghcr.io/${owner}/bayshore:${{ github.sha }}"
