name: Test Container Build
on:
  pull_request:
  push:

jobs:
  test-container-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build
        run: |
          cp .env.example .env
          cp config.example.json config.json
          docker buildx build --platform linux/amd64,linux/arm64 .
